### ISSUE TITLE
done

### ISSUE THREAD

**Issue by AnPogrebnyak** [Kateryna-Kalantyria/test_java#2]
Файлы конфигурации проекта и откомпилированный код не должны попадать в репозиторий. Это ркгулируется при помощи файла .gitignore
https://ru.stackoverflow.com/questions/542088/%D0%9A%D0%B0%D0%BA-%D0%BF%D1%80%D0%B0%D0%B2%D0%B8%D0%BB%D1%8C%D0%BD%D0%BE-%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%B8%D1%82%D1%8C-%D1%84%D0%B0%D0%B9%D0%BB-gitignore

Убери из репозитория папки:
.settings
bin
Файлы:
.classpath
.settings

**Comment by Kateryna-Kalantyria** [comment]
created file .gitignore
